# Generated by Django 5.2.1 on 2025-08-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_alter_club_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='coursol',
            field=models.ImageField(blank=True, null=True, upload_to='club_carousel/'),
        ),
        migrations.AddField(
            model_name='club',
            name='interest',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='schedule',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='tagline',
            field=models.TextField(blank=True, null=True),
        ),
    ]
