# Generated by Django 5.2.6 on 2025-12-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0006_club_coursol_club_interest_club_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="founded",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
