# Generated by Django 5.2.6 on 2025-12-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0007_club_founded"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="event_images/"),
        ),
    ]
