# Generated by Django 5.2.6 on 2026-01-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0009_eventprize_eventtimeline"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("date_posted", models.DateTimeField(auto_now_add=True)),
                ("is_important", models.BooleanField(default=False)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("official", "Official"),
                            ("club", "Club"),
                            ("event", "Event"),
                        ],
                        default="official",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
