# Generated by Django 5.2.6 on 2026-01-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0010_notice"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("event", "Event"),
                    ("meeting", "Club Meeting"),
                    ("academic", "Academic"),
                    ("cultural", "Cultural"),
                ],
                default="event",
                max_length=20,
            ),
        ),
    ]
