# Generated by Django 5.2.6 on 2026-01-18 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0011_event_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("winner_name", models.CharField(max_length=200)),
                ("position", models.CharField(max_length=100)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="achievement_photos/"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("date_awarded", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to="clubs.event",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_awarded"],
            },
        ),
    ]
