# Generated by Django 5.2.6 on 2026-01-18 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0012_event_is_completed_achievement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="is_completed",
        ),
        migrations.DeleteModel(
            name="Achievement",
        ),
    ]
